kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-shared-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  sharedv4: "true"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: px-shared-vol
  annotations:
    volume.beta.kubernetes.io/storage-class: px-shared-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: alpine
  name: alpine
spec:
  replicas: 2
  selector:
    matchLabels:
      run: alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: alpine
    spec:
      containers:
      - image: alpine:latest
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: px-shared-vol
      schedulerName: stork

